apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.16
        name: nginx
        resources: {
          limits: {
            cpu: 500m,
            memory: 512Mi
          },
          requests: {
            cpu: 200m,
            memory: 256Mi
          }
        }
        ports:
        - containerPort: 8080
